### ISSUE TITLE
Additional files created when running format

### ISSUE THREAD

**Issue by neelasha23** [ploomber/pkgmt#40]
When running `pkgmt format` some additional files are getting created :

```
CHANGELOGfw_ik7po.py
CONTRIBUTING4ljdtm9j.py
CONTRIBUTINGon8wadvu.py
README4o9pqb11.py
READMEfvfvpkmi.py
cte-improvements.ipynb
cte-improvements_mgfmaln.py
cte-improvementsyd4m38m8.py
doc/Untitled.ipynb
node_modules/
plot_error.ipynb
plot_errorbcauq0gm.py
plot_erroruv9u5mz9.py
sql_error.ipynb
sql_errorn86m4eed.py
sql_errort78k6xjg.py
yarn.lock
```

**Comment by edublancas** [comment]
These files are temporary and should be deleted after the command ends (unless you stop it in the middle). Are you having issues?

**Comment by neelasha23** [comment]
Yes if the command fails these files don't delete. The command failed with error : Too many files open

**Comment by neelasha23** [comment]
here's the trace:

```
(jupysql) neelashasen@192 jupysql % pkgmt format
Running: black .
All done! ✨ 🍰 ✨
2422 files left unchanged.
Running: nbqa black .
Traceback (most recent call last):
  File "/Users/neelashasen/miniforge3/envs/jupysql/bin/nbqa", line 8, in <module>
  File "/Users/neelashasen/miniforge3/envs/jupysql/lib/python3.10/site-packages/nbqa/__main__.py", line 772, in main
  File "/Users/neelashasen/miniforge3/envs/jupysql/lib/python3.10/site-packages/nbqa/__main__.py", line 635, in _main
  File "/Users/neelashasen/miniforge3/envs/jupysql/lib/python3.10/site-packages/nbqa/__main__.py", line 469, in _get_nb_to_tmp_mapping
  File "/Users/neelashasen/miniforge3/envs/jupysql/lib/python3.10/site-packages/nbqa/path_utils.py", line 59, in get_relative_and_absolute_paths
  File "/Users/neelashasen/miniforge3/envs/jupysql/lib/python3.10/pathlib.py", line 993, in cwd
OSError: [Errno 24] Too many open files

***black returned errors.***
```

**Comment by edublancas** [comment]
Ok, so this is an issue in nbqa, can you open an issue there?

The yarn.lock seems unrelated. Looks like coming from another process.

As a temporary measure, you can increase the open files limit (this is OS dependent)

Do you have any extra files in your repo? Because the `22422 files left unchanged` seems like a lot. Since you have a `yarn.lock`, maybe you have a `node_modules` directory? Maybe they were generated when we were working on the JupySQL frontend extension, and we don't need them anymore.
